[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "mechpy"
version = "0.1.0"
requires-python = ">=3.8"
description = "A mechanical engineer's Python toolbox built with Rust"
readme = "README.md"
license = { file = "LICENSE.txt" }
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "pyarrow>=17.0.0",
    "pytest>=8.3.5",
    "pytest-benchmark>=4.0.0",
]

[tool.maturin]
features = ["pyo3/extension-module"]

[dependency-groups]
dev = [
    "maturin>=1.11.5",
]
